### ISSUE TITLE
Clarify the relation with composed VPN

### ISSUE THREAD

**Issue by billwuqin** [boucadair/attachment-circuit-model#23]
https://www.ietf.org/archive/id/draft-evenwu-opsawg-yang-composed-vpn-03.txt

**Comment by boucadair** [comment]
The service-AC model does not make an assumption about the "internal" structure or even the nature or the service(s) that will be delivered over it. The customer does not have access to that view other than the ACes that are exposed. 

For example, draft-evenu has the following:

>                             +------v---------------+
>                             | Network Orchestrator |
>                             +----+---+-------------+
>                                  |   |
>                        +---------+   +-----------+
>                        |                         |
>                 +------+--------+         +------+---------+
>                 |Config manager1|         | Config manager2|
>                 +------+--------+         +------+---------+
>                        |                         |
>              +---------+-----------+  +----------+----------+
>              |      AS1 L2VPN      |  |      AS2  L3VPN     |
>   +-------+  | +------+   +------+ |  | +------+   +------+ |  +-------+
>   | Site1 +----+ PE11 +---+ PE12 +------+ PE21 +---+ PE22 +----+ Site2 |
>   +-------+  | +------+   +------+ |  | +------+   +------+ |  +-------+
>              +---------------------+  +---------------------+

The service-ac model can be used to provision the ACes to connect Site1 and Site2 as these are the only **visible*** one to the customer. If any configuration is required between PE12/PE21, this is handled at the network level since this will be viewed as a SAP(role-type=nni). 

evenu would be much more simple if it only manipulates ac-refs and focuses on the advanced service modelling specfic to the composed VPN case.
