### ISSUE TITLE
compute-only flag for feasibility check 

### ISSUE THREAD

**Issue by Ivan-Bykov-RBBN** [boucadair/attachment-circuit-model#34]
Following the corresponding flag in nbi-yang, we may consider adding "compute-only" flag to check that the ac with all its parameters may or may not be provisioned on EPE

**Comment by boucadair** [comment]
It is reasonable to have such feasibility check. Please refer to https://mailarchive.ietf.org/arch/msg/teas/A1ZIh6U2MSo5KAENu0X7Jh6dxtQ/.

However, I'm not sure yet a leaf is needed in the data model given that this is a functionality that is already provided by NETCONF for every configuration. FWIW, RFC6241 includes this parameter that can be used in an edit-config operation (using test-only would have the same effect):

```
test-option:  The <test-option> element MAY be specified only if
         the device advertises the :validate:1.1 capability
         ([Section 8.6](https://www.rfc-editor.org/rfc/rfc6241#section-8.6)).

         The <test-option> element has one of the following values:

         test-then-set:  Perform a validation test before attempting to
            set.  If validation errors occur, do not perform the
            <edit-config> operation.  This is the default test-option.

         set:  Perform a set without a validation test first.

         test-only:  Perform only the validation test, without
            attempting to set.
```

**Comment by boucadair** [comment]
I'm not questioning the feasibility check. I agree that this is a good feature. My point is that this is redundant with what you can do "natively" with NETCONF.

**Comment by vlopezalvarez** [comment]
I'm not familiar with the feasibility check process. Is it a sync procedure in the API? I mean the server does not answer until there is not confirmation that the process is executed?

**Comment by boucadair** [comment]
@vlopezalvarez, this is basically about "emulating" the processing of a request (that is, without putting it into effect if it succeeds).

**Comment by vlopezalvarez** [comment]
Is there any pointer (RFC or draft) to understand which is the expected behaviour from the server point of view? I know my question is not related to the model, but I want to be sure we have a common view on which will be the workflow.

Typically there are two types of APIs, sync and async. Sync APIs would get the POST message with the "feasibility-check" and it will wait to answer until the feasibility check is done. This may take some time, depending on the network side and request complexity. Moreover, this blocks the server. On the other hand, Async APIs would get the POST and answer back immediately acknowledging the reception of the request (not the feasibility). It is up to the client to poll the API to obtain and update of the operation.

**Comment by boucadair** [comment]
> Is there any pointer (RFC or draft) to understand which is the expected behavior from the server point of view?

Apart the confirm/confirmed commit in NETCONF, I'm not aware of any other RFC that describes this explicitly.

**Comment by robric** [comment]
I don't think we need a feaseability check for the AC itself, since it is not really meant to be used as standalone. 
Imho, this knob applies more for end-to-end services. For example, "compute-only" is part of Slice NBI data model. 
In this latter case - 5G slicing - the feaseability check is part of the slice request on which the AC is glued. 

Keep in mind that AC is more related to provide the right set connectivity information in a practical fashion (which is actually enforced together with the ad-hoc service slice). Additionally, there is no real computing here so the 'compute-only' naming would be confusing.

**Comment by boucadair** [comment]
double restconf support and then decide.
