### ISSUE TITLE
missing link in  ietf-ac-svc:bearer to PE/CSR device ID

### ISSUE THREAD

**Issue by Ivan-Bykov-RBBN** [boucadair/attachment-circuit-model#39]
How to link "customer-device:device-id" to "node-id" or "ietf-node-id"?

**Comment by Ivan-Bykov-RBBN** [comment]
Do we see the necessity to mention optionally interface ID / LAD bundle ID on both ends?

**Comment by boucadair** [comment]
> How to link "customer-device:device-id" to "node-id" or "ietf-node-id"?

@Ivan-Bykov-RBBN, I guess you mean the node ids in the provider's network as per:

```
   module: ietf-network
     +--rw networks
        +--rw network* [network-id]
           +--rw network-id            network-id
           +--rw network-types
           +--rw supporting-network* [network-ref]
           |  +--rw network-ref    -> /networks/network/network-id
           +--rw node* [node-id]
              +--rw node-id            node-id
```
If so, the provider's node-id is not exposed in the service model as this is internal to the provider. The mapping between a bearer and the PE is visible at the network model. That is defined in the companion network module (https://datatracker.ietf.org/doc/draft-boro-opsawg-ntw-attachment-circuit/)

```
  augment /nw:networks/nw:network/**nw:node**/sap:service/sap:sap:
    +--rw ac* [name]
       +--rw name                 string
       `+--rw ac-ref?              ac-svc:attachment-circuit-reference`
       +--rw ac-profile* [profile-id]
       |  +--rw profile-id    -> /nw:networks/network/ac-profile/name
```

**Comment by boucadair** [comment]
> Do we see the necessity to mention optionally interface ID / LAD bundle ID on both ends?

Not sure this is useful at service level because that information won't be useful for the provider to deliver the service. The current model allows to maintain multiple bearers bound to the same device-id without having to know if these bearers are locally bound to the same or distinct interfaces. The provider does not have that view anyway (unless the customer terminating point is managed by the provider).

If you have an example where the peer-sap/bearer-device-id are not sufficient to unambiguously identify an AC at the customer side, that would be helpful. Thanks, @Ivan-Bykov-RBBN
